### ISSUE TITLE
Resources are not available

### ISSUE THREAD

**Issue by SijieSong** [charliememory/Pose-Guided-Person-Image-Generation#14]
Hi, I'm trying to download the resources but I got :
You don't have permission to access /~liqianma/NIPS17_PG2/models/DF_model.zip on this server.

Could you please fix the problem?
Thanks!

**Comment by charliememory** [comment]
It's fixed now. Sorry for the inconvenient.

**Comment by smbadiwe** [comment]
> It's fixed now. Sorry for the inconvenient.

@charliememory Looks like this issue is back. I could not access any of the datasets / trained models. Will you please fix the problem again?

Thanks!

**Comment by abhishekiitd327** [comment]
@charliememory I am also facing the same issue.

**Comment by charliememory** [comment]
The problem was caused by the server maintenance and it is fixed now.
