### ISSUE TITLE
403 on the download page

### ISSUE THREAD

**Issue by ReSpike** [charliememory/Pose-Guided-Person-Image-Generation#41]
"You don't have permission to access ..."
Would you please to fix it?

**Comment by charliememory** [comment]
Hi, it's caused by our sever issue and may be fixed in a few days. Sorry for the inconvenience.

**Comment by emnab** [comment]
hi, I don't have permission to access /~liqianma/NIPS17_PG2/data/...
to download data 
help me, please

**Comment by charliememory** [comment]
Hi, the permission was changed due to the system update. It is fixed now.

**Comment by abh1kudo** [comment]
The issue is still happening in all links under resources heading , a fix would be greatly appreciated.

"Forbidden
You don't have permission to access /~liqianma/NIPS17_PG2/data/DF_train_data.zip on this server."

Thanks

**Comment by charliememory** [comment]
@abh1kudo, I asked our IT staff to reboot the server. It is fixed now.
